### ISSUE TITLE
Explore removing `context` import from `_bootstrap`.

### ISSUE THREAD

**Issue by jakehader** [terrapower/armi#1037]
When I was updating the code base in #998 I removed the `context` import thinking that it was unused. @john-science pointed out that this is probably needed, but it's not clear how exactly. It might be good to confirm this and if it is needed then possibly create a function that can be called for setup rather than just relying on import ordering and hoping for the best. This is difficult to test as-is.

**Comment by john-science** [comment]
The `context` / `bootsrap` logic in ARMI is pretty limiting. In particular, lately, it makes ARMI much less flexible for things like having more than one `Reactor` or `CaseSetting` in memory at one time.

I would also like ARMI to execute a lot less code at import time, as that would make using PIECES of ARMI, without the entire `App`/`Plugin` infrastructure a lot easier to accomplish.

**Comment by john-science** [comment]
This is the offending line:

https://github.com/terrapower/armi/blob/ab4a7ef49e95ed446a2d7243d2476703209fe6c6/armi/_bootstrap.py#L37

My gut reaction is this duplicate because we only call `_bootstrap` once, upon loading ARMI, and immediately after we import `context`:

https://github.com/terrapower/armi/blob/ab4a7ef49e95ed446a2d7243d2476703209fe6c6/armi/__init__.py#L61-L62
