### ISSUE TITLE
Tight coupling: improvements to user-interface

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#1094]
## Summary/Description
This is a follow up to PR #1033. 

During the review process, there was a general agreement that there should be an improvement to the user-interface for enabling tight coupling settings. This issue aims to coalesce the topics discussed.

--------------------------------------------

### Improvements to user-interface for tight coupling settings
In PR #1033, the `tightCouplingSettings` are tied to ARMI interfaces. @keckler and @drewj-usnctech both raised the argument of changing this to disconnect from the individual interfaces and instead interact with the ARMI composites directly. This new interface would look like the following (adapting from https://github.com/terrapower/armi/pull/1033#issuecomment-1376003683):
```yaml
tightCouplingSettings:
    core:
        parameter: keff
        convergence: 1e-4
    blocks:
        parameter: power
        convergence: 1e-3
```
Some additional insight: 
- https://github.com/terrapower/armi/pull/1033#pullrequestreview-1239712718
- https://github.com/terrapower/armi/pull/1033#issuecomment-1377650458

This would:
1. remove the ambiguity of parameters "belonging" to interfaces, since they really only "belong" to the ARMI data model. 
2. be a cleaner/clearer approach to managing convergence on different composite levels (e.g., converging on assembly-power vs block power, peak assembly temperature vs block temperature, multiple temperatures [clad, fuel, coolant, etc], etc...)

### Should this live on the `Operator`? 
In the review of #1033, @john-science brought up concerns with adding additional functionality to the `Operator` class. Below are a few comments pulled from the review
- https://github.com/terrapower/armi/pull/1033#discussion_r1060851225
- https://github.com/terrapower/armi/pull/1033#issuecomment-1382441235

So this begs the question, what would be the ideal approach?

@keckler had the idea of creating a new "TightCoupler" interface that sits on the end of the interface stack and is (presumably) active/executed if `o.couplingIsActive() == True`. 
- https://github.com/terrapower/armi/pull/1033#issuecomment-1379174808

@john-science also briefly mentioned/spit-balled the idea of an Operator subclass, `ConvergenceOperator`. 

I think both ideas have their own pros and cons. What do we think would be ideal? Do folks have any other ideas to consider as well?

**Comment by john-science** [comment]
@albeanth After I get back (April 10th), I would like to talk about this ticket.  Convergence is an important part of ARMI, and we are 90% of the way there to having this be an important feature in the system.

**Comment by slee-USNC** [comment]
Hello @john-science 
We have assorted our requests/questions In the order of descending priority.

1. Is it possible to select which physics/solvers are part of the iteration scheme? Eg. Physics1/Phisics2 iterate, once converged the Physics3 is executed? 
2. Can we let users to come up with their own convergence parameter? For now, a developer needs to write the parsing routine whenever there is a user's demand to a new convergence parameter.
3. Can we configure the behavior of ARMI after it failed to meet the convergence criteria after it exceeds the max number of iteration? We may want to fail immediately instead of moving on to the next node.
4. Can we switch between relative and absolute convergence criteria or have both at the same time so we can move on when either one is met(like moose)
5. Can we have more than one parameters per interface to evaluate the convergence?
6. Can we measure convergence on a specific time node instead of throughout the entire lifetime?
7. Is it possible to define different time grids on which the different plugins operates? For example, plugin1/plugin2 (physics1/physics2) on a finer time grid and physics3 on a coarse time grid?

**Comment by albeanth** [comment]
Hi @slee-USNC, while @john-science is on vacation I will take a stab at answering your questions!

> 1. Is it possible to select which physics/solvers are part of the iteration scheme? Eg. Physics1/Phisics2 iterate, once converged the Physics3 is executed?

This is currently not supported. This would require changes at the `Operator`-level within ARMI and likely creating a new subclass to manage tight coupling altogether with. Not impossible, but not supported right now.

> 2. Can we let users to come up with their own convergence parameter? For now, a developer needs to write the parsing routine whenever there is a user's demand to a new convergence parameter.

What sort of convergence parameter are you interested in? The unofficial plan, as I understand it, was to move use the parameters registered on the database to compute convergence. For example, we would converge on whichever parameters are listed. If this isn't what you are looking for, an example would be great!
```yaml
tightCouplingSettings:
    core:
        parameter: keff
        convergence: 1e-4
    blocks:
        parameter: power
        convergence: 1e-3
```
>3. Can we configure the behavior of ARMI after it failed to meet the convergence criteria after it exceeds the max number of iteration? We may want to fail immediately instead of moving on to the next node.

That is definitely doable, yes. If it's something you need/would want sooner than later, we could create a separate issue and get that put in.

> 4. Can we switch between relative and absolute convergence criteria or have both at the same time so we can move on when either one is met(like moose)

Hmmm. I'm not sure I am following the request. The way in which convergence is measured is currently hardcoded in each Application plugin. So if you could certainly have the core power be measured relative and another parameter in another plugin be measured via an absolute convergence criteria. 

> 5. Can we have more than one parameters per interface to evaluate the convergence?

Unfortunately, no, not in the current form. At least not easily. If/once we switch to an `Operator`-based approach as outlined above, this will be possible.

> 6. Can we measure convergence on a specific time node instead of throughout the entire lifetime?

This actually currently exists! See the setting `cyclesSkipTightCouplingInteraction` within https://github.com/terrapower/armi/pull/1173. 

> 7. Is it possible to define different time grids on which the different plugins operates? For example, plugin1/plugin2 (physics1/physics2) on a finer time grid and physics3 on a coarse time grid?

I think this could be possible. Though I'm not as familiar with this aspect of ARMI. I'll tag @keckler to see if he has any input here.

**Comment by keckler** [comment]
For point (7), here's my thoughts.

You are always free to change the interactions of different interfaces at each of the time nodes. So if you wanted to modify the `interactEveryNode` hook on an interface so that it doesn't actually execute at every node, that's easy enough to do. Just throw some logic in there like:
```python
# only actually run if we are on an even time node
if timeNode % 2:
    return
else:
    do whatever calculations...
```
 Obviously you could make that as sophisticated as you'd like.

This paradigm only allows one to skip interactions of certain interfaces on certain nodes, which means that the whole problem would still share a single time grid, just that some interface interactions are skipped. Effectively this mimics the difference between the interface hooks like `interactBOC` versus `interactEOC`, just at a deeper level.

If you want totally different time grids for different physics plugins, that is a different story and I would venture to say that will be very difficult to implement using the current ARMI setup. That would be pretty anathema to the entire ARMI design.

But to emulate something like that, you can define whatever time grid you want using the [detailed cycle history](https://terrapower.github.io/armi/user/inputs/settings.html#cycle-history). If you wanted to define some super weird time grid that was inclusive of all the time steps that were desired by your different plugins, and then include some logic in the various plugins to only execute on certain steps, then sure this is possible. It might get ugly pretty fast, depending on how much you actually want to have different time grids for each of your solvers. And then you will end up with prints to your databases at every one of those time nodes, so your DB might up pretty huge.

Does that make sense? @slee-USNC

**Comment by albeanth** [comment]
> So eventually, we'd like to know if ARMI can support an input structure like this:

I think this is reasonable. The feasibility of this will become clearer once we transition the convergence parameters off of the interfaces and onto the `Operator`.

**Comment by keckler** [comment]
If USNC would like to help in moving the convergence parameters to be as outlined above, I think we'd welcome the help :-)

**Comment by aalfonsi** [comment]
> If USNC would like to help in moving the convergence parameters to be as outlined above, I think we'd welcome the help :-)

@keckler We are willing to help on this development here. In order to maximize the efficiency of our development, can you provide some guidelines on how to approach this?

**Comment by aalfonsi** [comment]
> @aalfonsi I just wanted to touch base and let you know that we have not forgotten about this! We just have some internal deadlines that are creeping up and taking priority, currently.
> 
> After chatting with @john-science and @keckler about this yesterday, I am going to open up a discussion thread (and close this issue) so we (TP and USNC) can openly discuss and decide the specific focus of this work. I.e., what we want to do, why, and how. Once we have these items agreed upon, we will have specific development tasks identified and we can divvy up the work as appropriate to work together.

Perfect. Thanks a lot.

**Comment by albeanth** [comment]
Closing this issue and moving to a discussion https://github.com/terrapower/armi/discussions/1245
