### ISSUE TITLE
armi-example-app fails due to missing THaveCoolantVel Parameter in thermalSolver.py

### ISSUE THREAD

**Issue by bherlethtwo** [terrapower/armi#1111]
The `armi-example-app` fails due to missing `THaveCoolantVel` `Parameter` in `thermalSolver.py` in  `computeAxialCoolantTemperature()`.

The attribute is THaveCoolantVel is undefined.

**Comment by jakehader** [comment]
Thanks for the bug report! @john-science this could be related to some recent TH parameter clean ups from the TH spring cleaning tickets/PRs

**Comment by john-science** [comment]
First:

1. I really want our `armi-example-app` to be working.
2. I might move this ticket over to the [`armi-example-app` repo](https://github.com/terrapower/armi-example-app).
3. Sounds like I need to create some basic unit/integration tests for the example app.

The problem occurred on December 5th, during the week where I removed 100 unused Parameters, in [this PR](https://github.com/terrapower/armi/pull/1001).

As far as I can tell, that Parameter was never used in ARMI or in the `armi-example-app`.  We SET that parameter in the `armi-example-app`, but it's not used anywhere.  I should be able to safely remove that line without it affecting anything. I'll do that.

**Comment by john-science** [comment]
Well, this Issue is in the wrong repo, but oh well. 

I have opened a PR for this [here](https://github.com/terrapower/armi-example-app/pull/5).

**Comment by john-science** [comment]
@bherlethtwo  Can you try now?

I tried after [this PR](https://github.com/terrapower/armi-example-app/pull/5), and it works for me.

Thanks!

**Comment by bherlethtwo** [comment]
![armi-example-app-issue](https://user-images.githubusercontent.com/122124998/214414933-227a5b79-1690-48c6-ac72-004ebe93ef9d.jpg)
I've rebuilt everything using python version 3.9.13 and pulled from the 'main' branch of armi-example-app. Getting a validation error but I don't know any more than that. No logs in the myapp/logs directory.

**Comment by john-science** [comment]
Okay, I believe I just fixed a bug to that affect:

```
-            inspector.cs[CONF_OUTLET_TEMPERATURE] < 0.0,
+            lambda: inspector.cs[CONF_OUTLET_TEMPERATURE] < 0.0,
```

Sorry, I JUST added that line of code the other day.  That's a branch new bug I added to the system.  

That should work now.  Sorry for the hassle.

**Comment by bherlethtwo** [comment]
Pulled from the main branch of armi-example-app repository. Now it works!

**Comment by john-science** [comment]
Also, I just opened a [new ticket](https://github.com/terrapower/armi-example-app/issues/4) in the `armi-example-app`. These problems are clearly because there are no automated tests that run the app to make sure it stays up-to-date and working with ARMI.

This is easily solved, as we did for the [dragon-armi-plugin](https://github.com/terrapower/dragon-armi-plugin/tree/main/.github/workflows) repo.

I don't know HOW we ended up with untested code, but if I can find some time tonight or this weekend, I should be able to spin up a quick test that runs the `armiexample run anl-afci-177.yaml` test shown in the README file.  And we can not worry about these things cropping up any more.
