### ISSUE TITLE
Define flags doesn't work for a normal armi submit run

### ISSUE THREAD

**Issue by onufer** [terrapower/armi#1191]
This error is never hit when i run armi locally on our cluster. contact me for the directory for full example. 

![image](https://user-images.githubusercontent.com/50242044/220761378-a073100c-55d5-4ec7-aeaf-0a4185a01266.png)

**Comment by john-science** [comment]
Mark's result here is surprising, since we have [significant testing](https://github.com/terrapower/armi/blob/3e47ec6e6359870866502c9356747cf1da4f9515/armi/tests/test_user_plugins.py#L32) in ARMI for the `defineFlags()` feature on `UserPlugins`.

The tests even build an `App` from scratch and then load plugins.

Should be interesting.
