### ISSUE TITLE
Negative gap thickness upon thermal expansion

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1220]
Since the fuel-clad gap is a fluid, typically its dimension are specified using the dimension of the fuel OD and the clad ID. This means that the size of the gap changes as the fuel and clad thermally expand.

It turns out that if the thickness of your gap becomes negative due to the differential expansion between the two components, ARMI doesn't really care:
![image](https://user-images.githubusercontent.com/21959600/226770743-81534d3a-c246-4d41-86b4-27f090a6af8c.png)

I don't yet know what the full implications of this are, but this seems like a problem. At the very least, it is non-physical.

**Comment by ntouran** [comment]
We did intentionally allow negative gaps due to mass conservation issues in having fuel made up of many materials with different thermal expansion coeffs that would overlap. Without a full thermo-mechanical FEA model dealing with how the layers interact we figured the best we can do is just let them overlap and let users hook in fancier fuel performance models to get the 'real' dimensions as needed. We think this will generally be ok for most neutronic and thermal analysis. 

I can find the internal tickets from way back where we decided this was ok and necessary.

**Comment by jakehader** [comment]
Negative gap might be better treated as up to zero because it is a weird quirk though. The down side is that atom densities in some block will be different but it's hard to say that what is there now is accurate. Possibly conservative? It's an assumption of the model that should probably be declared somewhere though (maybe it's in the docs already).

Going with negative gap and volume might be something that has been embedded in our tools for treatment in TH and FP (or could be something not many know about!). It might be safer to go to zero to not allow expansion through solid components and then communicate this as a warning that can only be resolved by detailed modeling to justify the sizing or to dynamically update as a application based physics plugin/interface.

**Comment by keckler** [comment]
FWIW, ending up with a negative gap thickness will cause 1D XS generation with the lattice physics interface to bomb.
