### ISSUE TITLE
Some material modifications are allowed to be the wrong length

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1223]
We currently have a check that tries to ensure that material modifications in the blueprints are of the same length as the number of blocks in that assembly:

https://github.com/terrapower/armi/blob/db8dc8c28fbea8614cac6c2d9b39a8c624838719/armi/reactor/blueprints/assemblyBlueprint.py#L221-L243

There is apparently a corner case that isn't caught. 

If you have a `by block` and `by component` material modification with the same name on a given block, only one of those will be checked. This is because the method above builds a dict of which things to check, and the same dict keys get reused for `by block` and `by component` mods. So the first one gets overwritten by the second.

**Comment by ChristensenCode** [comment]
Why loop over the `paramsToCheck` to access the dict values instead of performing the checking of `modlist` against `self.blocks` on line 235? You could chain if-elif-else statements to handle the original values in the `paramsToCheck` dict. This paired with the doing the comparison of lengths on Line 235 would eliminate the need for the `paramsToCheck` dict altogether.

You could also move the formatted ValueError to a different function and call it if the check fails.

**Comment by john-science** [comment]
@keckler I found a unit test that _almost_ covers the situation already in ARMI:

https://github.com/terrapower/armi/blob/06351ae15deb1956888835723adb38fea6f66d57/armi/reactor/blueprints/tests/test_materialModifications.py#L112-L127

I think what we see here is that not only does the length of the by-block material modifications not get tested, it doesn't matter.  In the situation where we have by-component AND a by-block material modifications list, only one of them can be used, and the other is ignored/over-written.

Does that make sense?

> Now, this ticket makes it sound like you hit the problem you state in the wild, is that true?  What was the situation?

I just want to make sure I build as complete a solution as possible.
