### ISSUE TITLE
Neutronics array Parameters need setter

### ISSUE THREAD

**Issue by Nebbychadnezzar** [terrapower/armi#1286]
A user recently tried to do a restart calculation that used depletion and calculating DPA. He ran into the following:

```bash
File "\\[removed]\armi\physics\neutronics\globalFlux\globalFluxInterface.py", line 859, in updateFluenceAndDpa
    b.p.pointsCornerDpa + b.p.pointsCornerDpaRate * stepTimeInSeconds
TypeError: can't multiply sequence by non-int of type 'float'
```

This error suggests that `pointsCornerDpaRate` is a Python list, not a numpy array. This is likely occurring because the setter for this parameter in `parameters.py` is not set up to convert from a Python list to a numpy array. Such a setter is used with other parameters like `linPowByPin`.

https://github.com/terrapower/armi/blob/02d3d2b9b58bbb27b6d2f5c4b270fa98ea6c30f0/armi/physics/neutronics/parameters.py#L273-L282

This issue exists for `pointsCornerDpa`, `pointsCornerDpaRate`, `pointsEdgeDpa`, and `pointsEdgeDpaRate`.

**Comment by Nebbychadnezzar** [comment]
Is there any way to avoid having to manually type out this setter for each numpy parameter, @john-science? We're copying pasting the same function definition with slight renaming in order to define the setter.

**Comment by onufer** [comment]
to showcase, there are already 7 instances of this copy pasted code in parameter modules of the framework alone
![image](https://github.com/terrapower/armi/assets/50242044/7b1ca4ed-e6ea-44ee-afab-15424cb1bb1b)

**Comment by onufer** [comment]
there is probably a corner case where its not a list of ints or floats where it does need to be a list but try/except would probably be fine

**Comment by john-science** [comment]
Well, I think this is easy enough to solve. And maybe easy enough to refactor a little, so we are duplicating less code.

But in any other language than Python, it would be the user's job to make sure their input data is the right type.  Type coercion is never perfect, and though I can definitely do this thing, there will always be a loss of fidelity going from a "list of python floats" to a "numpy array of numpy floats".

**Comment by wcscherer** [comment]
Talked with @albeanth and confirmed through testing that [PR1292](https://github.com/terrapower/armi/pull/1292) solves the original data type issue I encountered.

**Comment by onufer** [comment]
the setter seems to work OK for most instances, but when you have a fresh reactor  the initial state can be a bit weird were its 
![image](https://github.com/terrapower/armi/assets/50242044/6c50bd7d-a182-43b3-a0fe-3f17588e1965)

Which, fine its None, easy to test. just thought i would call out this observation. probably no action needed if thats the expection

i will use
`if b.p.linPowByPin is None:`

rather than 
`if b.p.linPowByPin:`
(this cannot be used due to` ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`, but all or any cannot be called on None to my knowledge..)

SO suggests `.size`, but that also fails on None: `https://stackoverflow.com/questions/11295609/how-can-i-check-whether-a-numpy-array-is-empty-or-not`

Let me know if you have any suggestions @john-science  or if i am missing something. I will let you decide if it makes sense to re-open or if the 
`if b.p.linPowByPin is None:`
solution is good enough
