### ISSUE TITLE
Coverage for uniform mesh converter

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1538]
The coverage went down because the tests for nonuniform assembly conversion in the global flux interface used to exercise the geometry converter. The tests in question: 

https://github.com/bsculac/armi/blob/366afec6121d0056545a8db0127a52d6116014f1/armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py#L312 

and
 https://github.com/bsculac/armi/blob/366afec6121d0056545a8db0127a52d6116014f1/armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py#L231 

It is inappropriate for those tests to test the uniform mesh converter, and the test coverage went down when I narrowed the scope of the test.

_Originally posted by @bsculac in https://github.com/terrapower/armi/issues/1536#issuecomment-1847863284_

**Comment by john-science** [comment]
A lot of time has passed since this ticket was opened, so I don't know the `uniformMesh.py` now has [91.5% code coverage](https://coveralls.io/builds/66242893/source?filename=armi%2Freactor%2Fconverters%2FuniformMesh.py).

So, I will close this ticket.

(Also, the code coverage on global flux is [84%](https://coveralls.io/builds/66242893/source?filename=armi%2Fphysics%2Fneutronics%2FglobalFlux%2FglobalFluxInterface.py) now.)
