### ISSUE TITLE
Add sysinfo for linux

### ISSUE THREAD

**Issue by opotowsky** [terrapower/armi#1684]
We have a system info printout for Windows:
https://github.com/terrapower/armi/blob/5fffeb7d3c43c8f822d9e866e70af33d63d99ee2/armi/bookkeeping/report/reportingUtils.py#L194-L203

But haven't added one yet for linux. 

The recommended command is as follows, but it has a couple of problems and therefore needs some work. 
```
echo "Operating system:      $(cat /etc/redhat-release)" > systeminfo.log && lscpu | grep "Architecture:\|CPU(s) list:\|Model:\|CPU family:\|Model name:\|CPU MHz:\|Byte Order:\|Stepping:" >> systeminfo.log && echo "GPU Information:" >> systeminfo.log && lshw -class display | grep "*-display\|description:\|product:\|vendor:\|clock:" >> systeminfo.log
```

1. It's OS-specific (looking for `/etc/redhat-release`)
2. It's piping everything into `systeminfo.log` (we just want the string returned)

**Comment by jakehader** [comment]
I can provide a bit more here on how to integrate this with our existing system logging without `system info` or assuming a red hat Linux environment.

**Comment by john-science** [comment]
This is obviously a good idea; I will handle it. Jake, happily, I see some internal code you wrote to this affect.  So we can talk, but that code will help a lot.

**To external parties**, I will only test for [`"linux" in sys.platform`](https://stackoverflow.com/a/13874620/12875930); I will not be  covering other operating systems like OS2 or MacOS, because ARMI is not tested on those operating systems.
