### ISSUE TITLE
ctrl+c bug when ARMI is used interactively

### ISSUE THREAD

**Issue by dlangewisch** [terrapower/armi#180]
When ARMI is used interactively in an iPython session and execution is terminated with ctrl-c, the temporary directory (`FAST_PATH`) gets deleted. If one then attempts to create a new database with write permissions from the same iPython session, an `OSError` occurs because it attempts to create the database in a non-existent directory. 

Below is a simple script to reproduce the issue. It loads a reactor, sleeps for 5 seconds, then writes the reactor to a new database. If ctrl-c is issued during the first run and the script is run a second time, an error occurs when opening `db-out.h5`

```python
import time
import armi
from armi.reactor.flags  import Flags
from armi.bookkeeping.db import databaseFactory

def load_reactor_and_settings(dbname, cycle, node):
    """load reactor snapshot at (cycle, node)"""
    verbosity = armi.runLog.getVerbosity()
    with databaseFactory(dbname, "r") as db:
        if not db.hasTimeStep(cycle, node): 
            raise ValueError("cycle not found in the database file")
        r = db.load(cycle, node)
        cs = db.loadCS()
        armi.runLog.setVerbosity(verbosity)
    return r, cs

if __name__ == '__main__':
    r, cs = load_reactor_and_settings('db-in.h5', 0, 0)

    print('sleeping for 5 seconds to mimic real work')
    # hit ctrl-c here during the first run, then re-run 
    time.sleep(5)

    with databaseFactory("db-out.h5", "w") as db:
        db.writeToDB(r)
```

**Comment by ntouran** [comment]
Thanks, great bug. This happens because of a confluence of things:
* we register a Ctrl-C signal handler in the root `__init__.py` that cleans up temporary files. When you ctrl-c, the `FAST_PATH` directory gets deleted
* But the `FAST_PATH` variable lives on, now pointing to an empty directory!
* When you open a new DB in `w` mode, it *always* makes itself in the `FAST_PATH`. 
* But since that dir no longer exists, you get this error. 

Hack workaround is to re-create `FAST_PATH` in the open method if it doesn't exist, but that's no good b/c it will happen elsewhere as well. 

@youngmit suggested maybe using the `armi.context.Mode` stuff to check for `INTERACTIVE` and just not use the `FAST_PATH` at all in that case. That's a pretty good idea.

**Comment by ntouran** [comment]
The proposed PR works as you'd expect given your test code, I believe. Will finish review and merge soon.
