### ISSUE TITLE
Simplify the logging facilities

### ISSUE THREAD

**Issue by andfranklin** [terrapower/armi#1807]
Maybe it's just me, but [`runLog.py`](https://github.com/terrapower/armi/blob/e2ab9418f3c3b3b95d2f386ad671611452760622/armi/runLog.py) seems overly complicated. I'm hoping to start a conversation, and I'm happy to take care of cleanup once a consensus is reached.

I wouldn't be surprised if these facilities could be cleaned-up if we narrowed-in on what's _actually_ required, and throw-out anything that isn't essential. For example:

- Is it necessary to reset set the [global logger class](https://github.com/terrapower/armi/blob/e2ab9418f3c3b3b95d2f386ad671611452760622/armi/runLog.py#L689-L691)? Speaking from my personal experience, this has caused unnecessary difficulties.
- Is it necessary to [define new logging levels](https://github.com/terrapower/armi/blob/e2ab9418f3c3b3b95d2f386ad671611452760622/armi/runLog.py#L120-L131)? IMO, it probably is not necessary to make `extra`, `important` and `prompt` when there's already `info` and `critical`. As far as I know, there isn't clear guidance on when to use the new levels, and it's likely to lead to confusion. The logging module already provides [logging level guidance](https://docs.python.org/3/library/logging.html#logging-levels). Why not lean on this, and delete some code? It seems like we're reinventing the wheel.

Also, there is some [hacky](https://github.com/terrapower/armi/blob/e2ab9418f3c3b3b95d2f386ad671611452760622/armi/runLog.py#L694-L716) code that could be cleaned-up and will likely be more robust if [filelocks](https://py-filelock.readthedocs.io/en/latest/) were used.

_Please comment below if you have any other ideas for how `runLog.py` could be cleaned-up._

**Comment by john-science** [comment]
I strongly disagree with:

> `runLog.py` seems overly complicated

That file is ~300 lines of Python. And it has dozens of features that people have asked for, in great detail. For instance, please notice that there are three requirements in that file.

**Comment by john-science** [comment]
@andfranklin I do not see how this ticket is high priority.

* Is `runLog` broken? No. 
* Are any of our users experiencing problems with `runLog`? No.
* Is `runLog` too complicated?  (This is an opinion, but it is an extremely short ~300 line file. So, no. It's tiny, and simple.)

As such, this idea seems low priority to me at this time.


This ticket is entirely opinion-based. There are no bugs, and you do not suggest any new logging features. This can be seen as the concerns you raise are all subjective:

1. "Maybe it's just me, but runLog.py seems overly complicated"
2. "Speaking from my personal experience, this has caused unnecessary difficulties."
3. "It seems like we're reinventing the wheel."

So, let us cover these opinions one at a time:

1. This file is extremely short and simple (~300 lines of Python).
2. This is the most common practice in Python projects. And the Python standard library is designed with this in mind.
3. These bonus logging levels exist because our users requested them.  So they have to stay.



This suggestion you make will require many PRs in downstream repositories. As such, each new API-breaking change needs to be weighed for cost-benefit: the value of the change, versus the time cost of implementing (it in ARMI and downstream).

To that affect, I weight the cost-benefit of this idea to be negative, as I do not not see a clear feature that our users _need_.


There are many more high priority tickets in ARMI. I recommend looking at the project's issues to get a sense of more urgent needs.

**Comment by jakehader** [comment]
@john-science - I do think that there may be some simplifications we could could make to run log. As I was writing the GUI I had spent several days trying to understand the python logging and the functionality of the `_RunLog` class versus the `RunLogger`. While not super high priority or even high priority, I think that there may be some merit to either improving the documentation of what makes the subclassing different in the design from the python logger and perhaps moving this issue to a discussion board. @andfranklin - if you'd like to make a discussion topic on this and share some pain points or specific code improvement ideas that would be good. Let's start there before an issue or feature request.
