### ISSUE TITLE
Geom type testing on cores is not working correctly

### ISSUE THREAD

**Issue by onufer** [terrapower/armi#212]
In the Core class, we typically have code like:

`if self.geomType == geometry.GeomType.HEX:`

This does not work correctly. It is comparing string "hex" to enum HEX, which are not equivalent. Here is a failing unit test in reactors.py:

```
    def test_geometry(self):
        self.assertEqual(self.r.core.geomType, geometry.GeomType.HEX)

AssertionError: 'hex' != <GeomType.HEX: 1>
```
The issue is likely that in grid.blueprints we set:

`spatialGrid.geomType = self.geom`

But self.geom is a string. Instead, it should likely be getting the enum and setting to that.

I am happy to fix, but don't want to waste time fixing in a way that is not preferred and have to rewrite it. Please provide guidance.

**Comment by onufer** [comment]
@youngmit please provide guidance

**Comment by youngmit** [comment]
This is interesting... how did you bump into this, because I'm surprised that we haven't run afoul of this yet. Storing the grid `geomType` as a string under the hood makes sense, since we use that for serialization. There are a couple of options that I can think of:
 - make the string representation of the grid geom type private and convert to the enum in a `geomType` property
 - same as above, but store the geomType as a public attribute that doesn't go into the database (saves us the string operations each time we ask)
 - do the conversion on the Core side, mapping the string from the Grid to the enum as the return type (leaves grids alone, but same potential perf issues in evaluating the string every time)

**Comment by onufer** [comment]
I am also surprised, but the bug was introduced in March, so maybe people haven't exercised it enough.

I ran into it with the a new interface I am making. I expect a hex reactor, and I formalize this and have it raise an error if it is not a hex reactor. But then, my unit tests fail since the comparison doesn't work (even though the test reactor is a hex reactor).

Yeah, it sound like you are the best person to do this. Thanks!

**Comment by john-science** [comment]
I just noticed this old ticket. @onufer , is this bug still present?

If so, I'm not sure HOW we've gone this long without fixing it.

**Comment by john-science** [comment]
It appears to me this ticket was resolved in Dec, 2020:

https://github.com/terrapower/armi/commit/877e4bf5f422ad274018ff47f8cee0b05e0c611d#diff-960652692a507c38d352b15fcf65a4d0db496d10f04a42422551aea7c894a36eR214-R215
