### ISSUE TITLE
handle breaking string treatment in h5py 3.0 lib

### ISSUE THREAD

**Issue by ntouran** [terrapower/armi#243]
In cf74496463c5 we pinned the h5py requirement at `<3.0`. We should update the code to deal with the breaking change going forward and unpin this. Supporting info:

* Breaking change [is described here](https://docs.h5py.org/en/stable/whatsnew/3.0.html#breaking-changes-deprecations)
* H5py motivation behind the change is here: https://github.com/h5py/h5py/issues/1338

notably, h5py does not have windows wheels built for Python 3.9 and h5py<3.0 so this basically holds us back from going to python 3.9 at the moment.

**Comment by youngmit** [comment]
I've made some progress on this. Most of this is in the database implementation regarding reading input files. Due to mutual dependecy including updates to the scipy and numpy dependencies. The numpy update is leading to minor differences in some unit test values when comparing files. To address this, I've updated the file comparison utility to have it try parsing values as floats and compare with a relative epsilon. This should keep unit test passing when someone has version on either side of the update. Still fighting some weird crashes in pytest that provide no output, but returns various access violation-related error codes.
