### ISSUE TITLE
How to circumvent strict thermal expansion calculation

### ISSUE THREAD

**Issue by drewejohnson** [terrapower/armi#245]
As far as I can tell, any new materials added outside of ARMI must have thermal expansion data available to the rest of the application. I found this by making a test material, following the instructions in https://terrapower.github.io/armi/tutorials/making_your_first_app.html#adding-a-new-material on how to add this to the lookup path, and attempted to run the FFTF model. I keep hitting this section https://github.com/terrapower/armi/blob/9e7c2984eae29ad0bb9752f9769cc17a7d12fec0/armi/reactor/components/component.py#L837-L851 where ARMI attempts to expand the volume in my fake material.

Looking at the [docs](https://terrapower.github.io/armi/tutorials/materials_demo.html)
> For pure neutronics runs, mass density and composition is enough

so maybe there's a setting somewhere along the way? I tried disabling the `axialExpansion` and `detailedAxialExpansion` settings with no luck. 

It looks like each component is expanded based on `THERMAL_EXPANSION_DIMS` at construction
https://github.com/terrapower/armi/blob/9e7c2984eae29ad0bb9752f9769cc17a7d12fec0/armi/reactor/components/component.py#L724-L751

Any advice would be greatly appreciated. 

Using python 3.7.9 and armi 0.1.6 - b89b6c4168e14789a7bc1e8e4a816df24af6e1d0

**Comment by drewejohnson** [comment]
I guess a workaround would be to add
```python
from numpy import inf
from armi.reactor.components import Component
Component._TOLERANCE = inf
```
to the app `__main__.py` file but that doesn't feel ideal

**Comment by sombrereau** [comment]
would it be possible to see the error message and the if possible the material class definition?

**Comment by youngmit** [comment]
I think this happens when your Thot and Tinput temperatures are different in your input/component parameters. The idea with Thot and Tinput is to be able to specify dimensions as some as-built dimensions near room temperature Tinput, and let ARMI thermally expand the dimensions to a rough at-power temperature (Thot). If Thot and Tinput are different, the corresponding material needs to have expansion methods implemented.

Can you try making Tinput and Thot the same (make sure to define your dimensions accordingly!) and see if that helps?

**Comment by drewejohnson** [comment]
Setting `Thot` and `Tinput` to be identical works. Thanks!
