### ISSUE TITLE
Give Blocks a spatial grid by default under certain circumstances

### ISSUE THREAD

**Issue by youngmit** [terrapower/armi#319]
Blocks tend not to have spatial grids, and their pin components lack spatial locators. This is because historically, we have not really cared that much _where_ a pin is in particular; usually there are enough instances of the pin components to fit neatly(ish) into a given number of hex rings or whatever, so we infer their locations that way. They are also usually identical, so we never had to care which specific site a pin or collection of pins occupied.

Eventually we added the ability to get more specific in the input blueprints (see https://terrapower.github.io/armi/tutorials/walkthrough_lwr_inputs.html), but we never actually _required_ the user to provide grid layouts for their blocks, since it would break every input file that we've ever written, and going forward, having to explicitly define the layout of trivial blocks would be a major drag. As a result, in most hex reactor inputs, pretty much every Block has no `.spatialGrid`.

The expectation throughout the code that Blocks "just don't have grids" has led us to whip up grids ad hoc whenever they would be necessary, making (but almost never verifying) all sorts of assumptions about how stuff is laid out. I wouldn't be surprised if this leads to some interesting bugs, or the very least confusion, in cases where a Block has an interesting set of components. Best case scenario is that whipping up the grids where we do so isn't wrong and we are just potentially wasting time making and re-making grids, being too afraid to actually attach the grid to the block itself (and the locators to the components).

I propose that we take the step of actually defining a "trivial/canonical Block layout", and when a Block supports it (EDIT: and doesn't explicitly define one) _actually make a spatial grid for it_ at construction time. Then throughout the code, if we come across a block that _doesn't_ have a spatial grid, we will know that it wasn't just because the input writer just didn't bother, but because it's actually a weird block design and we should think carefully about just whipping up a grid for it.

First stab at a definition for "trivial":

> A block where all components have a multiplicity of either 1 or N, where N fits squarely in a number of locations that can be held by an given number of rings.

Thoughts?

**Comment by ntouran** [comment]
I like this idea. I think it's pretty safe as you defined it since having a grid is just extra info and shouldn't change any answers or numbers for plugins that ignore it. It will be quite useful to have for people who can use the pin level info.

**Comment by jakehader** [comment]
I agree with this and also think that it may uncover unexpected issues in client code related to "whipping up" block layouts. I believe that it would be safe to assume:

| **Core Grid Type** | **Block Grid Type** |
| Cartesian | Cartesian |
| Hexagon | Hexagon |
| RZT | `None` |

When determining whether a "pins" or all components fit into the grid will you be checking for geometry overlaps with the "duct" or "can" based on the pitch data or will you just be using the number of available locations? For example, you can jump between 217 pins and 271 pins, but if you define 218 pins then will this just not assume a `spatialGrid` and present a warning? I recommend that any implicit assignment of `spatialGrid` types be recorded and reported to the user in the STDOUT so that this is visible and easy to verify.

**Comment by youngmit** [comment]
> if you define 218 pins then will this just not assume a spatialGrid and present a warning

In my mind, ARMI would just throw up its hands and not even attempt to set a `.spatialGrid` for such a block, leaving it as None. I agree that reporting the generated grids to the user in the stdout is a good idea.

**Comment by youngmit** [comment]
Implemented in #323. Thanks, @chris10mckenz !
