### ISSUE TITLE
Component Parameter listing in user docs

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#354]
The [section in the user docs that outlines the various types of parameters](https://terrapower.github.io/armi/user/manual_data_access.html) provides links to dedicated pages where more extensive listings can be found (see [353](https://github.com/terrapower/armi/pull/353) for more info on recent updates to the links). The links for Reactor, Core, Assembly, and Block parameters all go to similar pages that provide cohesive and comprehensive listings of their respective parameters, including the names, descriptions, and units of each parameter. These tables are generated programmatically from the relevant source code. 

However no such page exists for the Component Parameters, and currently the Component Parameters link goes to a table embedded in a description of the Blueprints input file. In addition to this being inconsistent with the other links, it is further undesirable because the table that it links to is a mess and does not provide the same type of information as the other tables. It is therefore desirable to create a new page for Component Parameters which is in line with the other parameter definition pages and to link to it.

In addition, once this new page is complete it would be good to remove the (incomplete) Component Parameters table from the Blueprints input file and to retool that page so that duplicate and potentially confusing information can be avoided.

**Comment by jakehader** [comment]
#353 has been merged.

**Comment by john-science** [comment]
@keckler  Is this ticket complete?  I see a PR has been merged for it.

**Comment by keckler** [comment]
No, I don't think this ticket has been worked at all. The PR that was merged was for a related, but separate, issue. So still wide open.

**Comment by ntouran** [comment]
In order to accomplish this ticket:

* we need to make a new rst file called `doc/user/component_parameters_report.rst`
* In this file, we should add code along the lines of that in [here](https://github.com/terrapower/armi/blob/b709d3450f6b7a89376abed3a2bf9107bcfe39f2/doc/user/reactor_parameters_report.rst), but that loops over all subclasses of `Component` in the code and makes tables for each subclass found.  Maybe `CompositeModelType` will be useful for that?

That should be all
