### ISSUE TITLE
Explore immutable settings

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#371]
Currently, there are many places in the codebase where we call `getMasterCs()` and read in all the settings.  Slightly more troubling, there are many places in ARMI and in the plugins where we _change_ settings mid-run.

**Purpose**: explore how much havoc would be caused by making settings immutable.  

**Method**: change the settings API a bit to raise a `DeprecationWarning` every time a setting is altered.  Then test various real-world use cases to see how often (and where) this warning pops up. 

**Results**: report back on the prevalence and where these warnings pop up.

**Comment by john-science** [comment]
@youngmit  Could you assign this to me, please?  Thanks!

**Comment by youngmit** [comment]
Done!

**Comment by john-science** [comment]
Before I go about the business of refactoring our settings code to make the settings truly mutable, I have outlined below all the places in the ARMI framework we mutate settings mid-run.  I would like your opinion on which of these cases below is **not** a valid use-case for mutable settings.

From this list, I will generate all the sections of the codebase and workflows that need to be refactored, aside from just the settings code itself.

| Num | File | Method | Is Valid Mutation? |
| :-- | :--- | :----- | :-------------: |
| 0 | [armi/bookkeeping/snapshotInterface.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/bookkeeping/snapshotInterface.py#L72) | SnapshotInterface.activateDefaultSnapshots() | Y |
| 1 | [armi/cases/case.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/cases/case.py#L687) | `Case.writeInputs()` | ???  "This allows input objects that have been modified in memory to be written" |
| 2 | [armi/cases/inputModifiers/neutronicsModifiers.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/cases/inputModifiers/neutronicsModifiers.py#L32) | `NeutronicConvergenceModifier.__call__()` | Y |
| 3 | [armi/cases/suiteBuilder.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/cases/suiteBuilder.py#L170) | `SuiteBuilder.buildSuite()` | Y |
| 4 | [armi/operators/operator.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/operators/operator.py#L977) | `Operator.setStateToDefault()` | ??? designed for mutable things |
| 5 | [armi/operators/settingsValidation.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/operators/settingsValidation.py#L301) | `Inspector._inspectSettings()` | ??? several mutations here |
| 6 | [armi/operators/snapshots.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/operators/snapshots.py#L92) | `OperatorSnapshots.setStateToDefault()` | Y |
| 7 | [armi/physics/fuelCycle/settings.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/physics/fuelCycle/settings.py#L188) | `getFuelCycleSettingValidators()` | ??? This seems okay to me. |
| 8 | [armi/reactor/converters/parameterSweeps/generalParameterSweepConverters.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/reactor/converters/parameterSweeps/generalParameterSweepConverters.py#L47) | `SettingsModifier.convert()` | ??? |
| 9 | [armi/reactor/converters/parameterSweeps/generalParameterSweepConverters.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/reactor/converters/parameterSweeps/generalParameterSweepConverters.py#L65) | `NeutronicConvergenceModifier.convert()` | ??? |
| 10 | [armi/scripts/migration/m0_1_0_settings.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/scripts/migration/m0_1_0_settings.py#L61) | `_modify_settings()` | Y |
| 11 | [armi/scripts/migration/m0_1_6_locationLabels.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/scripts/migration/m0_1_6_locationLabels.py#L74) | `_modify_settings()` | Y |
| 12 | [armi/settings/caseSettings.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/settings/caseSettings.py#L230) | `Settings.loadFromInputFile()` | ??? |
| 13 | [armi/settings/caseSettings.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/settings/caseSettings.py#L259) | `Settings.loadFromString()` | ??? |
| 14 | [armi/settings/caseSettings.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/settings/caseSettings.py#L407) | `Settings.temporarilySet()` | ??? |
| 15 | [armi/settings/caseSettings.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/settings/caseSettings.py#L417) | `Settings.unsetTemporarySettings()` | ??? |
| 16 | [armi/settings/settingsRules.py](https://github.com/terrapower/armi/blob/73584062a24c135f323651f6bf2f95419ffbd168/armi/settings/settingsRules.py#L196) | `addToDumpSnapshots()` | ??? looks okay to me, but what is a "dump snap shot"? |

I will attempt to fill in the `Y`/`N` for "Is this a valid mutation?" in the table above. But if someone has a strong opinion, feel free to add a line to the able yourself.

**Comment by youngmit** [comment]
1 is one of those places where it should probably be making a new settings object with the new settings. Especially since it's making some decisions about where the blueprints and geom file [theses are borderline defunct and probably need deprecated, too, at some point. going to make an issue to this effect].

4: Not even sure what we need this for. Very odd... 6 is doing something similar. I am suspicious of this pattern.

5: The whole point of settings validation is to do a bunch of plugin-extensible checks and massage settings before they are even really interpreted for real. I still think the semantics of the settings validation should be that a Settings object `A` goes into the validation box and a new Settings object `B` pops out the other side.

8, 9 are fine, since the whole point is to twiddle settings from a base input and generate new inputs. As with validation, i think the fully-immutable approach makes the most sense here; the modified settings should be completely new objects, and the "base" Settings object should never be changed.

12, 13 is where settings come from in the first place, so deffo need to be able to modify/initialize the state of the settings.

14 is bad. This is the whole antipattern of settings modification, given a name. At least it will undo its modifications, but anywhere it's being used I would bet money there's another, cleaner way to do it. Either by not actually trafficking in `Settings` at all, or by making a new, temporary `Settings` object with your modified settings, then throwing it away when you're done. If there _are_ global side effects of the temporary setting modifications, refactoring around that might be a bit tricky, but pretty high priority.

16. Settings rules are essentially another approach to the Inspector settings validation, so also pretty fine. "dump snap shot" is a list of CCCNNN strings specifying cycle (C) and node (N) to perform snapshot analysis on. Providing one to the user when it's not specified is probably not a great idea anyways.

**Comment by john-science** [comment]
> 4: Not even sure what we need this for. Very odd... 6 is doing something similar. I am suspicious of this pattern.

**Fun Fact:** These two methods `setStateToDefault` are not used in ARMI. Though there are ~32 places in the code that assumes `cs["runType"]` exists, and depends on the value. It is, apparently, a very important setting, with an entire file devoted to providing the options (`armi/operators/runTypes.py`). My current guess is that these two staticmethods are either entirely unused, or used in some way by a plugin.

Any opinion about number 7? There is a *lot* of code here to validate fuel cycle settings, so my bias is to assume all that functionality is necessary, and this mutation is good.

Thanks for all your input!

**Comment by john-science** [comment]
A note on progress.  We are 75% of the way through making settings immutable.  Much progress was made.

The major thing left to do is remove the fact that someone sneaky can still do:  `cs['mySetting'] = 1` as long as `cs['mySetting']` already exists and has some value.

I initially thought this would be a minor change, but _whoa_ was I wrong. This breaks half the unit tests in ARMI, and I have personally seen a dozen plugins that depend on this functionality.  (Though I believe at least part of the reason for this could be solved by removing all settings that only belong to one plugin. That would be a big lift on it's own though.)

**Comment by john-science** [comment]
In the past ~9 months, the changes we've made to making Settings more immutable have stabilized and become standard.

They are not 100% immutable yet, sadly.  As making that happen would require a hard backwards-compatibility-breaking rewrite of a huge swath of the codebase.  And stopping people from doing things in Python is notoriously hard.

So what we have now appears to be the accepted middle-ground.  And while I will always keep my eye on this, I will close the ticket for now.
