### ISSUE TITLE
Replace old reports code with new reports code

### ISSUE THREAD

**Issue by youngmit** [terrapower/armi#410]
@chris10mckenz gave us new Reports functionality. We should start using it. Highest priority should be given to the diffuse code that's reaching into the old reports data from all over the place (looking at you https://github.com/terrapower/armi/blob/6efb915e1ad5d19b5d30a14c93bab14b75d33ea6/armi/settings/caseSettings.py#L335).

**Comment by john-science** [comment]
@youngmit  What is the status of this?

**Comment by john-science** [comment]
The current status of this is we still have "reports" and "newReports" in the repo:

https://github.com/terrapower/armi/tree/8b5485c4ac4f988a680af7444c985698cdc9cbd4/armi/bookkeeping/report

Unfortunately, the "newReports" are used alongside the "reports" in the `ReportInterface`, so there is no way to fix the naming problem without breaking the API.

But we should go through and break the API, because the names are confusing to people and I get questions.   I think it is too late to remove the "new report" tools; that ship has sailed.

**Comment by john-science** [comment]
This ticket has been superseded by the more general ticket: https://github.com/terrapower/armi/issues/793
