### ISSUE TITLE
trackAssems should be False by default

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#511]
The default behavior for `trackAssems` should be turned to `False`:

https://github.com/terrapower/armi/blob/08e276833069478e8dd6c40c0dcbedf1e5de3456/armi/settings/fwSettings/globalSettings.py#L606-L612

The code change is obviously minor, but some work will need to be done looking around the ARMI ecosystem to make sure this doesn't hurt anyone's workflow.

**Comment by ntouran** [comment]
This setting effectively turns on indefinite appending of all discharged assemblies to the spent fuel pool container. Obviously in infinitely long or large runs this inevitably fills up RAM. Long ago, we used assemblies there to track history. Today we can just read the output database from disk when history is needed within a run (e.g. to build an irradiation history for a fuel performance calc). 

If we turn this off completely, then nothing will ever get added to the SFP. We still can allow fuel handler subclasses to make that kind of decision and move themselves, which is honestly probably a better approach.

**Comment by keckler** [comment]
If this change is implemented, I think some work will also need to be done on [`removeAssembly`](https://terrapower.github.io/armi/_modules/armi/reactor/reactors.html#Core.removeAssembly) to make its intention clear. Right now, because `trackAssems` and the `discharge` option in `removeAssembly` both default to `True`, the behavior when turning one of them to `False` is clear. But if `trackAssems` defaults to `False` while `discharge` defaults to `True`, I think it becomes potentially confusing to the user when trying to use either of them.

**Comment by john-science** [comment]
> ...I think it becomes potentially confusing to the user when trying to use either of them.

This is an interesting point. I hadn't seen the `discharge` option there before. So that might be a bit of a wrinkle.
