### ISSUE TITLE
How do I get pin locations within a block?

### ISSUE THREAD

**Issue by veeshy** [terrapower/armi#55]
I'd like the xy locations of pins within a grid defined at the block level. I got to the spatialGrid below using the c5g6 tutorial input:

```
import armi
if not armi.isConfigured():
    armi.configure(armi.apps.App())

o=armi.init(fName="./cases/c5g7/c5g7-settings.yaml")
b = o.r.core.getBlocks()[4]  # a mox block
g = b.spatialGrid
g

<Grid -- 5024459576
Bounds:
  None
  None
  None
Steps:
  [1.26 0.   0.  ]
  [0.   1.26 0.  ]
  [0. 0. 0.]
Anchor: <mox B0006A at A0001A XS: A BU GP: A>
Offset: [0.63 0.63 0.  ]
Num Locations: 1057>
```

I'd expect 17x17=289 locations but I see 1057 in the above output. Also, `len(g.getAllIndices())` returns 1024.

ps: I actually want this on a hex based reactor, just using the LWR input so we have the same input to work with.

**Comment by ntouran** [comment]
The pin coordinates are stored on the `Component`s which are children of the block. This block has a few children:

```
>>> b.getChildren()
[<Circle: mox low fuel>,
 <Circle: mox medium fuel>,
 <Circle: mox high fuel>,
 <DerivedShape: moderator>,
 <Square: guide tube>,
 <Square: fission chamber>,
 <Square: pitch>]
```

This case treats all the low fuel pins as the same composition but they are specified by input in different locations. These coordinates are stored as the `spatialLocator` on each of these `Composite` objects. So for example:

```
>>>low = b.getComponent(Flags.FUEL| Flags.LOW) 
>>>for loc in low.spatialLocator: 
>>>    print(loc.getGlobalCoordinates())                                                                                                                                                                           
[11.34 32.76 32.13]
[12.6  32.76 32.13]
[13.86 32.76 32.13]
...
```

Or even more fun: 
```
for f, c in zip(flags, colors): 
    x,y=[],[] 
    pin = b.getComponent(Flags.FUEL| f) 
    for loc in pin.spatialLocator: 
        xi,yi,z = loc.getGlobalCoordinates() 
        x.append(xi) 
        y.append(yi) 
    plt.scatter(x,y,color=c) 
plt.show()
```
should give 
![image](https://user-images.githubusercontent.com/53948397/78942488-b03cfe80-7a6e-11ea-807c-a17244a86b93.png)

I am putting a big warning in the tutorial because these kinds of multi-index subassembly grids are pretty new and not used much throughout ARMI. Our subassembly pins in hex assemblies are being migrated into this new system. 

It might be interesting to take the ANL-AFCI-177 tutorial and give it sub-assembly pin maps like these but in hexes. That input deck at the moment doesn't have good subassembly pin location information, as you may have seen.

**Comment by ntouran** [comment]
Oh by the way, the grid on the block that you were looking at is kind of infinite so it's not too meaningful to look at. That is admittedly a bit confusing. As pins are added it auto-generates new spatial locators.

**Comment by veeshy** [comment]
Awesome! Yeah, I started with the `Component` level since that made sense and stopped short at `spatialLocator` because I didn't quite get I could iterate over it. I figured the next logical place would be in `Block` since it had a grid and that's where my question was, makes sense that Components have the useful info.

Thanks for the code snippet too.

**Comment by ntouran** [comment]
No prob! Thanks for the good questions. Helps a lot to see what isn't clear. 

Also also, `b.getNumPins` will count up the number of pins. It does actually skip the guide tubes and the fission chamber in this case because they're not defined by the ARMI framework as "pins", so you'll get 264. You can use `b.getNumComponents(Flags.GUIDE_TUBE)` to get those. Or you can use `b.getNumComponents(None)` to get the full 289. This method factors in the `multipliticy` of each component, whereas `len(b.getChildren)` only gives 7 (from the list shown in my previous comment... 7 distinct components in this block).

**Comment by veeshy** [comment]
Ah, cool, I dig all the convenience functions.

Another one similar to this so I'll dump it on this thread, if a pin map was inputted as periodic, how do you reconstruct the full map?

**Comment by ntouran** [comment]
We use the geometry converters in `armi.reactor.converters` to expand various symmetries, but the one you're talking about is not implemented in there at the moment. 

(FYI [we updated the LWR tutorial ](https://terrapower.github.io/armi/user/tutorials/walkthrough_lwr_inputs.html)to incorporate some things from this thread.)
