### ISSUE TITLE
`logs` folder is always created whenever `armi` is imported

### ISSUE THREAD

**Issue by joshuavictorchen** [terrapower/armi#602]
An empty `logs` folder is created in the current working directory whenever the `armi.context` module is imported, which is whenever `armi` itself is imported. Here's the stack trace for context (no pun intended):

https://github.com/terrapower/armi/blob/7d9ef5f8c0db459da167e3330fc6aa932d0255ce/armi/__init__.py#L61
https://github.com/terrapower/armi/blob/7d9ef5f8c0db459da167e3330fc6aa932d0255ce/armi/_bootstrap.py#L37
https://github.com/terrapower/armi/blob/7d9ef5f8c0db459da167e3330fc6aa932d0255ce/armi/context.py#L333

This behavior results in an army of `logs` folders scattered across the user's working drive wherever an ARMI application has been executed, even if they were not used at all. We should consider creating the `logs` folder at runtime, as needed, instead of upon import.

**Comment by ntouran** [comment]
Reasonable request for sure. It'd be nice to not make that many log folders. We could maybe default to a location in `APPDATA`/profile space so as to not clutter rundirs. I think we only need the logs folders if the number of MPI nodes is >1 anyway, so that should be pretty easy to detect and avoid.
