### ISSUE TITLE
Should n2n be scaled by keff?

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#611]
In [`globalFluxInterface.calcReactionRates`](https://github.com/terrapower/armi/blob/master/armi/physics/neutronics/globalFlux/globalFluxInterface.py#L979), the number of neutrons produced through fission is scaled by `keff` to account for situations when `keff` isn't equal to 1.0:
https://github.com/terrapower/armi/blob/4fcea827c16b471e067fff809f775caec54e2de8/armi/physics/neutronics/globalFlux/globalFluxInterface.py#L1056-L1059

Two lines later in the same method, the number of neutrons produced through (n,2n) reactions is calculated. However, that term is _not_ scaled by `keff`, even though it is a production term similar to fission.

Should the (n,2n) production rate also be scaled by `keff`?

Or alternatively, should the `keff` scaling on the fission term be removed? If the flux being used is already scaled to account for non-unity `keff`, then I don't think that the reaction rate should be scaled again.

Not sure which option would be correct here, but I think that the two values are being calculated inconsistently. But of course let me know if I'm wrong.

**Comment by Nebbychadnezzar** [comment]
My guess is that this looks right. I imagine that DIF3D is solving "leakage + absorption = scattering + 1/keff * fission". The solver achieves equality by finding the k-eff value that forces this balance to occur; so, the fission rate (by conceptually scaling nu) is the knob that's adjusted to artificially make this happen. If k-eff is not exactly 1.0, then an adjustment was necessary to the fission rate to achieve balance. The other terms in the equation are not affected by this adjustment, such as (n,2n) reaction rate (which I am guessing is buried in the scattering term?).

After the solver is done, if you were to get the flux from the solver and multiply it by the fission XS alone, that fission rate would be wrong by a factor of 1/keff because that was the adjustment factor that was needed to achieve balance. All other edits using "flux * cross section" would be correct, though.

**Comment by ntouran** [comment]
Agree with @Nebbychadnezzar. Extra info: n,2n production is indeed buried in the scattering term as its own special scattering matrix. The loss part of (n,2n) capture is in the absorption term. [An example n,2n production matrix from an ISOTXS file may be found here.](https://terrapower.github.io/armi/gallery/framework/run_isotxs2_matrix.html#sphx-glr-gallery-framework-run-isotxs2-matrix-py)
