### ISSUE TITLE
Optional input param in `plotAssemblyTypes` is not optional

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#701]
`plotAssemblyTypes` has one non-optional parameter, `blueprints`:
https://github.com/terrapower/armi/blob/cda41da2de1e601ead0dbca51c9fe57223e8d970/armi/utils/plotting.py#L694-L702

But examination of the function shows that if the `assems` parameter is passed in, then `blueprints` is never used:
https://github.com/terrapower/armi/blob/cda41da2de1e601ead0dbca51c9fe57223e8d970/armi/utils/plotting.py#L735-L736

So in fact `blueprints` should be optional.

**Comment by john-science** [comment]
There is definitely a problem there.

It looks like someone tried to define a function that required either input A or input B, but not both.  But they didn't know how to do that, because that is not an idea that Python really supports with it's default/optional arguments logic.

The method should be cleaned up, for sure.
