### ISSUE TITLE
Material Expansion Failure

### ISSUE THREAD

**Issue by alexhjames** [terrapower/armi#715]
Some materials in their `linearExpansionPercent`, for example Zr, do not provide any output beyond the temperature range. The `checkTempRange` verifies if the temperature is in the correct range and provides a warning if the temperature is not in the correct range. After that warning, the function should continue to provide an extrapolated value. Right now, it returns `None` which results in a very confusing stack trace. 

For example: 
![image](https://user-images.githubusercontent.com/103008519/173696356-4489a12f-4aa3-4799-88aa-a05ad8f16b5b.png)

**Comment by alexhjames** [comment]
In other words, in Zr.py, there should be an "else" in this chunk of code. This should be checked for similar errors in all other materials as well. 
![image](https://user-images.githubusercontent.com/103008519/173699974-814d61e1-391e-4248-9691-db4c42e201d3.png)

**Comment by john-science** [comment]
@ntouran @jakehader @keckler 

Funny thing here, if you pass in a value of, say, 290K or 1809K, this method just returns `None`.  Oh, it raises a Warning, but the code will continue on anyway. And the developer on the other end better have put in a catch for that `None`.

A better programming practice here would be to raise an `Error` and fail the run. That way you don't have invalid non-scientific garbage in a simulation that runs for days on the cluster.  It keeps the results always "correct" and "valid", which I like.

Alternatively:

* We could return a "no expansion" for in input temp below the lower limit (which seem correct).
* And/or/maybe... fail for input temp above the upper limit.

Any opinions before I start coding?

**Comment by alexhjames** [comment]
@john-science One additional thought, if you're going to kick out with an error when you're outside the range, can you please make there be a way to ask what the allowed temperature range is? For example, if I'm building a tabular list of CTE vs temperature (for use with Abaqus say), right now there is no way to know what is the allowable range of inputs to this function without an error. The 293 and 1800 are hard coded directly in the method.

**Comment by keckler** [comment]
I think @alexhjames 's last point here highlights an important drawback of our materials in the framework -- that is, they are pretty ad-hoc. There is _some_ structure, and generally all the material classes follow the same patterns, but right now any given material class could be in any state of completeness and their methods could return basically anything.

It would be nice if we pinned these down a little more.

I know that we generally use other materials for our own internal work, but the public material classes are somewhat of a mess right now.

**Comment by bmingst** [comment]
mat_props has been modified to prevent any output beyond the set maximum and minimum temperatures.  It will throw an error.  You will be able to query the limits with "get_min_degrees_C()" and "get_max_degrees_C()".  Interestingly, the mat_props data (Zr.yaml) from the TP Materials Handbook uses a different reference (V. Petukhov, "Thermal expansion of zirconium in the solid phase," High Temperatures - High Pressures, vol. 35/36, pp. 15-23, 2003/2004.) and has different limits: 20C to 873C.)  Are we using Kelvin in ARMI and Celcius in mat_props?  Not sure if this is much of a problem.

**Comment by john-science** [comment]
Yeah, I think providing better access to important materials data from the class would be better.

Maybe we could have a discussion and come up with a bit of a list of things we'd like to see in the ARMI materials library?  This one point definitely stands as a good one, but if I'm going to make design changes to the materials tooling, it would be better to have a full set of goals, rather than just one idea.

**Comment by john-science** [comment]
> L_hot / L_cold = e^(alpha1*dT1) * e^(alpha2*dT2)

Just to be clear, are `alpha1`, `dT1`, `alpha1`, and  `dT1` all scalars/floats?  They're not 2D arrays or matrices, right?

**Comment by alexhjames** [comment]
Correct! All scalars. The two quantities `alpha1 * dT1` and `alpha2 * dT2` are essentially already calculated in the function currently as `dLLhot` and `dLLcold` except they should be divided by 100 to convert from percent to a decimal.

**Comment by john-science** [comment]
Actually, it looks like this problem is already solved.  The `linearExpansionPercent()` methods all call `Material.checkTempRange()`:

https://github.com/terrapower/armi/blob/d04e1be8937c44e506dfcd5ff25459fca24af6cf/armi/materials/material.py#L544

But we have set ARMI so that, by default, we only print out a warning when someone ask for a value outside the valid temperature range. If we set this to `True`, the code would immediately fail and you would get a clear error message:

https://github.com/terrapower/armi/blob/d04e1be8937c44e506dfcd5ff25459fca24af6cf/armi/materials/material.py#L40

It seems people have come before us on this one, and decided the opposite of what we want.

It's certainly an easy fix on my end. Perhaps I would want some help testing to see if this kills anyone's simulations, or if this would ruin anyone's workflow.

**Comment by john-science** [comment]
I think there are at least two things that need to be done here:

1. Enforce `FAIL_ON_RANGE = True`, and enforce that _all_ ARMI materials have a `checkTempRange()` in the linear expansion and density methods.
2. Find some way to expose the min/max temperatures for materials linear expansion, density, thermal conductivity, etcetera curves.
3. Have a bigger discussion about how the Materials library in ARMI could be improved.

**Comment by john-science** [comment]
As far as (1) above... I switched `FAIL_ON_RANGE` to `True` by default, and that fixes that bug.  ARMI Materials are a lot more consistent. But suddenly, I've found some lacking valid data ranges in ARMI materials.  In particular, even our ARMI unit tests no longer run, because the `test reactor` requires materials slightly outside our current "valid temperature" bounds.

Where can I get references to fill in these data holes?

* `Sodium` - current lower bound for `density` is `97.85 C`, but I need it down to `20 C`.  (Note, `Sodium` is a solid at `97.72 C`.)
* `B4C` - current upper bound for `linear expansion` is `500 C`, but I need it up to about `600 C`.
* `Uranium Oxide` - current lower bound for `thermal conductivity` is `300 C`, but it needs to be `293.15`.

**Comment by john-science** [comment]
I have opened a PR here to solve number (2) in this PR:

https://github.com/terrapower/armi/pull/762

**Comment by john-science** [comment]
I am going to close this issue, as I believe the original problem of not being able to determine the min/max temperature bounds for temp-dependent curves has been solved.

To address the broader concerns about consistency and predictability in ARMI materials, we have opened a Discussion here:

https://github.com/terrapower/armi/discussions/767

I'm hoping to get some good, actionable ideas out of that discussion.
