### ISSUE TITLE
`fuelPerformance.plugin` can't handle multiple different pins with bond

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#731]
https://github.com/terrapower/armi/blob/4894a56c4c5498272d47b6bc307765eb207f4801/armi/physics/fuelPerformance/plugin.py#L66-L87

In that function, there is a call to `bond = b.getComponent(Flags.BOND, quiet=True)`. This call can only pick up a single component with the `BOND` flag. If there are multiple components with the `BOND` flag, `getComponent()` fails with a ValueError: https://terrapower.github.io/armi/_modules/armi/reactor/composites.html#ArmiObject.getComponent

```
ValueError: Multiple components match in <IFR1BlanketBlock B0082-002 at ExCore XS: A BU GP: A> match typeSpec Flags.BOND: [<Circle: gap_U19Pu10Zr>, <Circle: gap_U8Pu10Zr>, <Circle: gap_U10Zr>]
```

I guess _okay_, I understand why it is difficult to set a parameter named `bondBOL` for an entire block when there are multiple potential values for it. 

But also, this is a scenario that is reasonably likely to occur. So we should probably be able to handle it. Not sure what to do about it though...

On another note, this does not feel like something that should be in the framework. It feels like it belongs in a plugin, because even the concept of a bond inside the pins is pretty specific to a small subset of reactor designs.

 @sammiller11235 Do you have any thoughts on this?

**Comment by sammiller11235** [comment]
Hmm, seems like we need to add some logic to deal with multiple bonds. If you add an "s" to getComponent:  `bondS = b.getComponents(Flags.BOND, quiet=True)` does that get you the 3 bonds from the components? If you so, you could add some logic like: `b.p.bondBOL = sum([sum(bond.getNuclideNumberDensities(bond.getNuclides())) for bond in bondS])`

**Comment by keckler** [comment]
...and what if the different bonds are different materials? :-\

**Comment by sammiller11235** [comment]
Hmm, good points. It looks like the parameter `b.p.bondBOL` is used in a couple of places to reduces the nuclide densities based on a bondRemovalFraction (see `crucible._applyBondRemovalFractions` and `fuelPerformance.utils.enforceBondRemovalFraction`), so those functions will have to get updated as well to handle this change. 

I think if the bonds are different materials that is reason to fail with a NotImplementedError. Otherwise, as long as the bonds are the same material and if the removal can be handled appropriately I think this doesn't need a warning . Let me know if you'd like some help with the logic to sum or remove the bonds
