### ISSUE TITLE
Swap the ordering of the XS group manager and fuel handler in the interface stack

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#839]
Right now the crossSectionGroupManager comes before the fuelHandler in the interface stack.

This is not ideal because then whatever is eventually shuffled into the core for that cycle would not have been around for the cross section group manager to account for. This could be particularly an issue for fuel shuffled back into the core from the spent fuel pool, which might be at high burnup.

This fix should hopefully be a simple swap of the ordering of the interfaces. I don't anticipate any dependency issues, but we'll find out!

**Comment by ntouran** [comment]
> Right now the crossSectionGroupManager comes before the fuelHandler in the interface stack.

This is designed to allow users to first compute cross sections and then let the fuel manager fire of a branch search where it tries out ~hundreds of different potential fuel management operations in parallel on a HPC. Since all fuel management operations should use the same XS set, this reduces the number of times you have to run lattice physics. 

Though it looks like we removed the docs for the branch search capability  (#828). I have to double check on that but I didn't think we meant to remove that key capability of ARMI.

**Comment by keckler** [comment]
Right, so the ordering makes sense for that use case. But probably for most other uses, I would assume that people want the group manager to come after the fuel handler so that what is in the core during that cycle is accurately captured.

Maybe there is a way for the ordering to be configurable based on the workflow? 

(See also #947 )

**Comment by john-science** [comment]
@sombrereau @drewejohnson Would it affect your ARMI applications if we moved the default location of the XSGroup manager in the stack order?
