### ISSUE TITLE
Parameters defined by UserPlugin do not make their way to the parameter collection

### ISSUE THREAD

**Issue by drewj-usnctech** [terrapower/armi#939]
Very interested in the power of the `UserPlugin` interface! I'm trying to get a situation going where a `UserPlugin` defines some new parameters, maybe because it's an in-development feature not ready for prime time, and see how it works.

```python
from typing import List
from random import random

from armi.plugins import UserPlugin, HOOKIMPL
from armi.reactor.reactors import Core
from armi.interfaces import Interface, InterfaceInfo, STACK_ORDER
from armi.reactor.parameters import (
    ParameterDefinitionCollection,
    ParamLocation,
    Category,
)


class ExternalPlugin(UserPlugin):
    """Demo external plugin that exposes some trivial interfaces"""

    @staticmethod
    @HOOKIMPL
    def exposeInterfaces(cs) -> List[Interface]:
        return [
            InterfaceInfo(
                STACK_ORDER.BEFORE + STACK_ORDER.BOOKKEEPING, ExternalInterface, {}
            )
        ]

    @staticmethod
    @HOOKIMPL
    def defineParameters():
        import pdb

        # Set a breakpoint if we hit this call
        pdb.set_trace()

        return {
            Core: _coreRNGParam(),
        }


def _coreRNGParam() -> ParameterDefinitionCollection:
    params = ParameterDefinitionCollection()

    with params.createBuilder() as pb:
        pb.defParam(
            "rng",
            description="Random number",
            default=None,
            location=ParamLocation.VOLUME_INTEGRATED,
            categories=[Category.volumeIntegrated],
        )

    return params


class ExternalInterface(Interface):
    name = "Demo external interface"

    def interactEveryNode(self, cycle, node):
        self.r.core.p.rng = random()

```

When I run this, I see the `ExternalInterface` correctly in the stack
```
=========== 05 - Demo external interface        Init            ===========
```
but it falls with `ExternalInterface.interactEveryNode` for cycle 0, node 0
```
===========  Triggering EveryNode - cycle 0, node 0 Event ===========
=========== 01 - main                           EveryNode - cycle 0, node 0 ===========
=========== 02 - fissionProducts                EveryNode - cycle 0, node 0 ===========
=========== 03 - xsGroups                       EveryNode - cycle 0, node 0 ===========
=========== 04 - history                        EveryNode - cycle 0, node 0 ===========
=========== 05 - Demo external interface        EveryNode - cycle 0, node 0 ===========
[err ] <class 'AssertionError'>\nTrying to set undefined attribute `rng` on a ParameterCollection!\<traceback object at 0x7fce39e1b3c0>
```
with
```
AssertionError: Trying to set undefined attribute `rng` on a ParameterCollection!
```

## Request

It would be valuable to have `UserPlugins` be able to define and modify their own parameters. Is this a workflow that's possible?

## Version data

ARMI 6a4eb3b55d3ab2e3c7651a76d0034af34c37b0f4 -- `0.2.4`

**Comment by john-science** [comment]
That's interesting.

`UserPlugins` are designed (due to level-of-complexity and ease-of-use concerns) to bar parameter renames:

https://github.com/terrapower/armi/blob/06b839ef7ceea1c56799d9189017e4c4a4a41d99/armi/plugins.py#L656-L658

I thought I had tested adding new parameters and not had any trouble.  So I will have to test that out and see what happened.  I love that you gave me your working example, by the by. Thanks for that!  That always helps.

(P.S. Did you know that in Python 3.7+, you can just write `breakpoint()` instead of importing `pdb` and do the `set_trace` thing?  Just FYI, it's less tying.)

**Comment by drewj-usnctech** [comment]
@john-science wanted to ping this. Any update?

**Comment by john-science** [comment]
Sorry, @drewj-usnctech . Looking at it now.  

I can reproduce your bug in the last ARMI `main` commit:  75c2c87299

**Comment by john-science** [comment]
Okay, @drewj-usnctech , the problem seems to be that we define Parameters during the `armi.configure(MyApp())` step:

https://github.com/terrapower/armi/blob/75c2c872995f4072335a1209ffc5bfc95391dea1/armi/__init__.py#L315

And that comes before we read the settings file and are aware of the `UserPlugin`s.  So, right now this is apparently a limitation of the `UserPlugin` feature.  But it's not clearly defined as such, like we do for the `defineParamRenames()` hook.

So, that's the situation.  And there seem to be two options ahead of me:

1. Find a way to fix this scenario, and build `UserPlugin` support for the `defineParameters` hook.
2. If that's hard or impossible, clearly describe that `defineParameters()` is unsupported for `UserPlugins`, like `defineParamRenames()`.

Let me play with it for a few minutes and see if I can handle (1), before giving up and moving on to (2).

**Comment by drewj-usnctech** [comment]
Thanks for poking around @john-science 

Maybe naïve question: how feasible would it be to update the parameter collection after collecting it from the plugin manager? Like, as user plugins are loaded from settings, calling `newParams = newPlugin.defineParameters()`, and then `parameters.update(newParams)`

I can see a problem where I run a case with a user plugin in one environment, and then try and load the database in another environment where the user plugin is not defined. I think this might be related to why user plugins don't allow new settings? Well maybe not if the user plugins aren't processed until the setting file is loaded

We have a user group here that would really benefit from this capability. So if you do find that option 2 is the way to go, let me know and I'll see if we can brainstorm on it

**Comment by john-science** [comment]
@drewj-usnctech I have been sitting here playing with this.  These `ParameterCollections` were _really_ designed to be set once and uneditable afterward.  So far, I haven't had any luck in opening them up and jamming in another `Parameter` from a `UserPlugin`.  

I'll play with it for a bit longer.  Tricky though.

**Comment by john-science** [comment]
@drewj-usnctech  Okay, I am going with (2) for now.  Please see my explanation in [this PR](https://github.com/terrapower/armi/pull/967).

I guess my question is:  Why can't you use a regular `ArmiPlugin`?   Are they just too much effort?  If so, maybe my efforts would be better spent trying to make it easier for ya'll to use the normal `Plugin` system.

We'll figure something out.

**Comment by drewj-usnctech** [comment]
Thanks for investigating @john-science. I totally understand your rationale.

The background is we have some functionality that we cannot provide to our entire internal user group, but is required by some internal projects. We also don't want to "pre-define" their sensitive parameters in the main distribution. So, we wanted to allow the projects to define their own external plugins where they define, compute, and store these sensitive values. Without introducing those fields into the primary distribution of our ARMI application.

What we are leaning towards doing is having these projects create their own ARMI app by subclassing the primary app and add `ArmiPlugins` there. It feels clunky but it will probably work
